Change RenderPassAttachment texture member to be owning
turanszkij/WickedEngine pull request #562
Opened 2022-09-09 19:48 UTC by jdswebb

- Change RenderPassAttachment texture member to be owning (`const Texture*` -> `Texture`). Due to on-demand PSO creation, the description on the textures can potentially be read at any point during the RenderPass's lifetime. The previous use of a `Texture*` meant that a _particular reference_ of a texture had to be kept live.
    - There are only around 150 RenderPassAttachment objects live at any moment in Wicked Engine, and they are created up-front. So the additional cost of ref counting and description duplication should not be an issue.
- Changed the RenderPassAttachment builder functions to not accept null textures. The graphics device does not actually handle them being null and would crash.

Testing:

Loaded up a terrain scene in the editor with d3d12 and vk.

2022-09-09 19:49 UTC, jdswebb commented on WickedEngine/wiGraphics.h
>  	struct RenderPassAttachment
Btw - this moved down because now it must be defined after `Texture`.

2022-09-10 08:02 UTC, turanszkij requested changes
I checked the build, but black screen flickering is happening at some points. For example creating a new terrain causes random flickering. Looks like only in dx12,

2022-09-10 09:44 UTC, jdswebb commented
Fixed that check, I can't seem to reproduce any d3d12 terrain flicker so far.

2022-09-10 09:51 UTC, turanszkij commented
The whole screen is flashing to black for me if I create a new terrain, but not the terrain itself. Also some flashes to black when opening fighting game script for example, but then it only happens for one frame (probably when it switches the renderpath). Also when exiting the script with ESC for one frame..

2022-09-10 09:57 UTC, jdswebb commented
With debug device I get an error, so hopefully the same cause even though I've not been able to see it - will have a look.

2022-09-10 10:14 UTC, jdswebb commented
It's because of this dummy texture:

```
		internal_state->dummyTexture.desc.format = desc->format;
		internal_state->dummyTexture.desc.width = desc->width;
		internal_state->dummyTexture.desc.height = desc->height;
		internal_state->renderpass = {};
		wi::helper::hash_combine(internal_state->renderpass.hash, desc->format);
		internal_state->renderpass.desc.attachments.push_back(RenderPassAttachment::RenderTarget(internal_state->dummyTexture));
```

I could stop errors by not checking texture.IsValid() in `pso_validate`, because in this case the texture is not valid but its description is.

2022-09-10 11:07 UTC, turanszkij commented
removing that IsValid check seems to work fine for me. Could you make the change on your branch?

2022-09-10 11:36 UTC, jdswebb commented
No errors on d3d12 or vk for me now and the new assert is never hit.

2022-09-10 12:12 UTC, turanszkij approved these changes

2022-09-10 12:12 UTC, merged